import { motion } from "framer-motion";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="pt-24 lg:pt-32 pb-16 lg:pb-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <Link
              to="/"
              className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-8"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>

            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold text-foreground mb-4">
              Terms of Use
            </h1>
            <p className="text-muted-foreground mb-12">
              Effective Date: March 2025
            </p>

            <div className="prose prose-invert prose-lg max-w-none space-y-8">
              <p className="text-muted-foreground leading-relaxed">
                Please read these Terms of Use carefully before using the App. By accessing or using our trading signals application, you agree to be bound by these Terms. If you do not agree, do not use the App.
              </p>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  1. Acceptance of Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  By creating an account or using any feature of the App, you confirm that you are at least 18 years old, legally capable of entering into binding agreements, and that you have read, understood, and agree to these Terms.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  2. Nature of the Service
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  The App provides automated trading signal ideas generated by a rules-based algorithmic strategy. These signals indicate potential trade entry points, stop-loss levels, and take-profit targets for supported financial instruments.
                </p>
                <div className="p-4 rounded-lg bg-accent/10 border border-accent/20">
                  <p className="text-foreground font-medium">
                    Important: The signals provided are for informational and educational purposes only. They do not constitute financial advice, investment recommendations, or an offer to buy or sell any financial instrument.
                  </p>
                </div>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  3. No Financial Advice
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We are not a licensed financial advisor, broker, or investment manager. Nothing in the App should be construed as personalised financial advice. You should consult a qualified financial adviser before making any investment or trading decision.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  4. Trading Risk Disclosure
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  Trading financial instruments including forex, commodities, indices, and cryptocurrencies involves substantial risk of loss. You may lose some or all of your invested capital. Past performance of our signals does not guarantee future results. You acknowledge and accept that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Markets can move against signal directions due to unforeseen events.</li>
                  <li>Slippage, spread widening, and low liquidity can affect trade execution prices.</li>
                  <li>No strategy, algorithm, or signal service can guarantee profits.</li>
                  <li>You are solely responsible for all trading decisions made on your account.</li>
                  <li>We bear no liability for losses arising from the use of our signals, whether executed manually or automatically.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  5. Account Connectivity & Auto Trading
                </h2>

                <h3 className="text-xl font-display font-medium text-foreground">
                  5.1 Connecting a Trading Account
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  The App allows you to connect an external trading account via a third-party integration (MetaAPI). When you connect an account, you provide read/write access credentials. You agree that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>You are the authorised account holder of any account you connect.</li>
                  <li>We do not store your broker password. Credentials are handled securely via the MetaAPI integration layer.</li>
                  <li>You remain fully responsible for maintaining the security of your trading account credentials.</li>
                </ul>

                <h3 className="text-xl font-display font-medium text-foreground">
                  5.2 Auto Trading
                </h3>
                <div className="p-4 rounded-lg bg-destructive/10 border border-destructive/20">
                  <p className="text-foreground font-medium">
                    Auto trading is disabled by default. We will never place trades on your account unless you explicitly enable the auto trading feature within the App.
                  </p>
                </div>
                <p className="text-muted-foreground leading-relaxed mt-4">
                  When auto trading is enabled, you acknowledge and agree that:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Trades will be placed automatically on your connected account when a signal is triggered for your subscribed symbols.</li>
                  <li>Each automated trade uses a fixed fractional risk of 1% of your account balance. This cannot be modified.</li>
                  <li>You have read and accepted the Auto Trading Disclaimer presented within the App before enabling this feature.</li>
                  <li>You may disable auto trading at any time from the account settings screen.</li>
                  <li>We are not liable for any losses, missed trades, or duplicate trades resulting from connectivity issues, platform outages, or unexpected market conditions.</li>
                </ul>

                <h3 className="text-xl font-display font-medium text-foreground">
                  5.3 Your Responsibility
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  Even with auto trading enabled, you remain fully and solely responsible for all activity on your trading account. You should monitor your account regularly and disable auto trading if you do not wish trades to be executed.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  6. Subscriptions & Premium Features
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  Certain features of the App, including access to additional trading pairs and signals, require a premium subscription. Subscription terms, pricing, and cancellation policies are presented at the point of purchase within the App and are subject to the terms of the relevant app store (Apple App Store / Google Play).
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  7. Prohibited Use
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  You agree not to:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>Use the App for any unlawful purpose.</li>
                  <li>Attempt to reverse-engineer, scrape, or extract signal data for redistribution.</li>
                  <li>Share your account credentials with third parties.</li>
                  <li>Use the App in jurisdictions where trading signals or auto trading services are prohibited.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  8. Intellectual Property
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  All content, algorithms, signal logic, design, and software within the App are proprietary. You are granted a limited, non-exclusive, non-transferable licence to use the App for personal use only. No rights are transferred to you beyond this licence.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  9. Limitation of Liability
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  To the maximum extent permitted by applicable law, we shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the App, including but not limited to trading losses, missed opportunities, or technical failures.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  10. Changes to Terms
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to update these Terms at any time. Continued use of the App after changes are published constitutes acceptance of the revised Terms. We will notify you of material changes via the App or by email.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  11. Governing Law
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms are governed by and construed in accordance with applicable law. Any disputes shall be resolved in the competent courts of the applicable jurisdiction.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-display font-semibold text-foreground">
                  12. Contact
                </h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you have questions about these Terms, please contact us through the support section of the App.
                </p>
              </section>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;
